# Generated by Django 3.2.18 on 2023-02-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('RecoveryProporation', models.CharField(max_length=50)),
                ('TotalCases', models.CharField(max_length=50)),
                ('NewCases', models.CharField(max_length=50)),
                ('TotalDeath', models.CharField(max_length=50)),
                ('NewDeath', models.CharField(max_length=50)),
                ('TotalRecovered', models.CharField(max_length=50)),
                ('NewRecovered', models.CharField(max_length=50)),
                ('ActiveCases', models.CharField(max_length=50)),
                ('SeriousCritical', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'World',
                'verbose_name_plural': 'Worlds',
            },
        ),
    ]
