# Generated by Django 3.2.18 on 2023-02-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230216_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='worlds',
            name='world_id',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
