# Generated by Django 3.2.18 on 2023-02-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_worlds_world_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('continent', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('RecoveryProporation', models.CharField(max_length=50)),
                ('TotalCases', models.CharField(max_length=50)),
                ('NewCases', models.CharField(max_length=50)),
                ('TotalDeath', models.CharField(max_length=50)),
                ('NewDeath', models.CharField(max_length=50)),
                ('TotalRecovered', models.CharField(max_length=50)),
                ('TotalTests', models.CharField(max_length=50)),
                ('Population', models.CharField(max_length=50)),
                ('NewRecovered', models.CharField(max_length=50)),
                ('ActiveCases', models.CharField(max_length=50)),
                ('SeriousCritical', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countrys',
            },
        ),
    ]
