# Generated by Django 3.2.18 on 2023-02-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_country_fatality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Worlds',
        ),
    ]
